config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, controllers: { registrations: 'registrations'}
  resources :users, only: [:show, :edit, :update] do
    collection do
      get :thank_you
    end
  end
  resources :categories, only: [:show]
  resources :lists, only: [:new, :index, :show] do
    collection do
      get :empty
    end
  end
  resources :products, only: [:show]

  namespace :admin do
    root to: "lists#index"
    resources :lists
  end

  constraints subdomain: "api" do
    scope module: :api, defaults: { format: :json } do
      namespace :v0 do
        resources :likes, only: [:create, :update]
        resources :lists do
          member do
            post :add_product
          end
          resources :list_items, only: [:show]
        end
        resources :list_items
        resources :products
        resources :stores do
          collection do
            get :search
          end
        end
        resource :user do
          collection do
            post :like
            post :unlike
            post :comment
          end
        end
      end

      namespace :v1 do
        resources :comments, only: [:show]
        resources :likes, only: [:create, :update]
        resources :lists do
          member do
            post :add_product
          end
          resources :list_items, only: [:show]
        end
        resources :list_items
        resources :products
        resources :stores do
          collection do
            get :search
          end
        end

        resources :users, only: [:show]
      end
    end
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  belongs_to :user
  has_many :items, class_name: "ListItem", dependent: :destroy
  has_many :products, through: :items
  has_many :scores
  has_and_belongs_to_many :categories

  scope :most_active, -> { where("products_count > 0").order(current_score: :desc, products_count: :desc, created_at: :asc) }
  scope :most_popular, -> { where("products_count > 0").order(total_score: :desc, products_count: :desc, created_at: :asc) }
  scope :most_products, -> { where("products_count > 0").order(products_count: :desc, created_at: :asc) }
  scope :needs_help, -> { where(products_count: 0).order(:created_at) }

  scope :most_active_by_category, lambda { |category_name|
    joins(:categories).
    where('categories.id = categories_lists.category_id
           AND categories_lists.list_id = lists.id
           AND categories.name = ?', category_name).
    order(current_score: :desc, products_count: :desc, created_at: :asc)
  }
  scope :most_popular_by_category, lambda { |category_name|
    joins(:categories).
    where('categories.id = categories_lists.category_id
           AND categories_lists.list_id = lists.id
           AND categories.name = ?', category_name).
    order(total_score: :desc, products_count: :desc, created_at: :asc)
  }
  scope :most_products_by_category, lambda { |category_name|
    joins(:categories).
    where('categories.id = categories_lists.category_id
           AND categories_lists.list_id = lists.id
           AND categories.name = ?', category_name).
    order(products_count: :desc, created_at: :asc)
  }

  validates :name, :user, presence: true

  def self.scope(scope, params = nil)
    scope = scope || "most_active"
    if params.present?
      List.send("#{scope}_by_category", params)
    else
      List.send(scope)
    end
  end

  def self.from_amazon_listmania_url(url)
    doc = Nokogiri::HTML(open(url))
    user = User.first
    list = List.create(name: doc.css("h1.largeTitle")[0].content.titleize, user: user)
    doc.css("input[name^='asin']").each do |input|
      sku = input["value"]
      begin
        product = Product.where(type: "AmazonProduct", sku: sku).last || Product.create(type: "AmazonProduct", sku: sku)
        list.add_product(product, user)
      rescue
        puts "#{sku} failed"
      end
    end
  end

  def add_category(category)
    if !category_ids.include?(category.id)
      categories << category
      Category.increment_counter(:lists_count, category.id)
    end
    save
  end

  def add_product(product, user)
    item = items.where(product_id: product.id).last || items.create(product: product, user: user)
    calculate_minimum_price
    calculate_maximum_price
    item
  end

  def contributor_breakdown
    @contributor_breakdown ||= Hash[scores.where(scorable_type: "User").group(:scorable_id).sum(:weight).sort_by{|k, v| v}.reverse]
  end

  def contributor_ids
    contributor_breakdown.keys
  end

  def contributor_points
    contributor_breakdown.values
  end

  def contributors
    User.find(contributor_ids).index_by(&:id).slice(*contributor_ids).values
  end

  def calculate_minimum_price
    update_column(:minimum_price_cents, products.minimum("price_cents"))
  end

  def calculate_maximum_price
    update_column(:maximum_price_cents, products.maximum("price_cents"))
  end

  def calculate_scores
    calculate_current_score
    calculate_total_score
  end

  def calculate_current_score
    update_column(:current_score, scores.sum(:weight))
  end

  def calculate_total_score
    update_column(:total_score, scores.sum(:weight))
  end

  def default_image(category=nil)
    if category
      items_ordered_by_rank.includes(:product).where(products: { category_id: category.id }).first.product.image.url(:profile)
    else
      items_ordered_by_rank.first.try(:product).try(:image).try(:url, :profile) || "http://placehold.it/300x300"
    end
  end

  def items_ordered_by_rank
    items.order(rank: :asc, created_at: :asc)
  end

  def items_ordered_by_most_likes
    items.order(likes_count: :desc, created_at: :asc)
  end

  def likes_count
    items.sum(:likes_count)
  end

  def minimum_price
    Money.new(minimum_price_cents)
  end

  def maximum_price
    Money.new(maximum_price_cents)
  end

  def maximum_likes_count
    items.maximum(:likes_count)
  end

  def recalculate_ranks(start, finish)
    ordered_items = items_ordered_by_most_likes
    ordered_items[start..finish].each do |item|
      item.update_column(:rank, ordered_items.index(item))
    end
  end
end

app/controllers/admin/lists_controller.rb
class Admin::ListsController < AdminController
  def index
    @lists = List.order(created_at: :desc).paginate(page: params[:page], per_page: 25)
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to admin_list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update_attributes(list_params)
      redirect_to admin_list_path(@list)
    else
      render :edit
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/api/v0/lists_controller.rb
class API::V0::ListsController < API::BaseController
  skip_filter :authenticate, only: [:show, :index]
  respond_to :json

  def index
    @lists = List.scope(params[:scope], params[:scope_params])
    render :index
  end

  def show
    @list = List.find(params[:id])
    render :show
  end

  def create
    @list = List.new(list_params.merge({user: current_user}))

    if @list.save
      render :show
    else
      render json: { class: "list", errors: @list.errors }, status: :unprocessable_entity
    end
  end

  def add_product
    @list = List.find(params[:id])
    @product = Product.find(params[:product_id])

    if @item = @list.add_product(@product, current_user)
      render :add_product
    else
      render json: { class: "list", errors: @list.errors}, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.permit(:name)
  end
end

app/controllers/api/v1/lists_controller.rb
class API::V1::ListsController < API::BaseController
  skip_filter :authenticate, only: [:show, :index]
  respond_to :json

  def index
    @lists = List.scope(params[:scope], params[:scope_params])
    render :index
  end

  def show
    @list = List.find(params[:id])
    render :show
  end

  def create
    @list = List.new(list_params.merge({user: current_user}))

    if @list.save
      render :show
    else
      render json: { class: "list", errors: @list.errors }, status: :unprocessable_entity
    end
  end

  def add_product
    @list = List.find(params[:id])
    @product = Product.find(params[:product_id])

    if @item = @list.add_product(@product, current_user)
      render :add_product
    else
      render json: { class: "list", errors: @list.errors}, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.permit(:name)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  def index
    @lists = List.all.paginate(page: params[:page], per_page: params[:per_page])
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def empty
    @lists = List.needs_help
    render "index"
  end
end

app/helpers/list_helper.rb
module ListHelper
  def list_price_range(list)
    dollar_min = number_to_currency list.minimum_price, precision: 0
    dollar_max = number_to_currency list.maximum_price, precision: 0
    "<span class=\"js-list-minimum-price\">#{dollar_min}</span><span class=\"#{"hide " if dollar_min == dollar_max}js-list-price-range\"> - <span class=\"js-list-maximum-price\">#{dollar_max}</span></span>".html_safe
  end

  def list_display_row_size(lists_count)
    case lists_count
    when 2
      6
    when 4, 8
      12
    end
  end

  def list_display_column_size(lists_count)
    case lists_count
    when 2
      12
    when 4, 8
      6
    end
  end
end

app/views/admin/lists/index.html.erb
<div class="">
  <%= link_to "New List", new_admin_list_path, class: "phxs pvxxxs bg-4 bg-3-hover c-13 c-15-hover" %>
</div>
<table class="mtm full-width">
  <thead>
    <tr>
      <th class="fwl">
        Title
      </th>
      <th class="fwl">
        Created At
      </th>
      <th class="fwl">
        Products
      </th>
      <th class="fwl">
        Ratings
      </th>
      <th>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td>
          <%= link_to list.name, admin_list_path(list) %>
        </td>
        <td>
          <%= list.created_at.strftime("%m/%d/%y") %>
        </td>
        <td>
          <%= list.products_count %>
        </td>
        <td>
          <%= rand(12) %>
        </td>
        <td>
          <%= link_to "edit", edit_admin_list_path(list) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate(@lists) %>

app/views/admin/lists/new.html.erb
<div class="fsl">
  New List
</div>
<div class="row nmhxs">
  <div class="col-sm-6 phxs">
    <%= form_tag v0_lists_url(host: api_domain, subdomain: api_subdomain), remote: true, class: "js-lists-api-form js-admin-lists-form-new" do %>
      <div class="mtm-plus">
        <div class="fsxxs">
          <%= label_tag :name %>
        </div>
        <div class="fss">
          <%= text_field_tag :name, nil, class: "paxxxs bss bwas bc-8 full-width" %>
          <div class="hide js-lists-api-form-error" data-input-name="list[name]"></div>
        </div>
      </div>
      <div class="mtm-plus">
        <%= submit_tag "Create", class: "paxxxs bss bwas bc-8 full-width" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/lists/show.html.erb
<div class="phm pbm ptxs bg-15 bss bwas bc-13">
  <div class="row nmhxs">
    <div class="col-sm-8 mtxs phxs fss">
      <%= link_to list_path(@list) do %>
        <%= @list.name %> <i class="fa fa-circle fsxxs <%= @list.active? ? "c-green" : "c-red" %>" title="<%= @list.active? ? "active" : "inactive" %>"></i>
      <% end %>
    </div>
    <div class="col-sm-4 phxs mtxs c-8 fss text-right-sm">
      <%= pluralize(@list.products_count, "Product") %>
    </div>
  </div>
</div>
<div class="phm pbm ptxs mtxs bg-15 bss bwas bc-13">
  <% @list.items.each do |item| %>
    <div class="row nmhxs mtm-plus">
      <div class="col-sm-2 phxs">
        <%= image_tag item.product.image.url(:profile), class: "img-responsive" %>
      </div>
      <div class="col-sm-8 phxs fsxs">
        <div class="fwl">
          <%= item.product.name %>
        </div>
        <div class="fws">
          <%= item.product.manufacturer %>
        </div>
      </div>
      <div class="col-sm-2 phxs">
        POINTS
      </div>
    </div>
  <% end %>
</div>
<div class="phm pbm ptxs mtxs bg-15 bss bwas bc-13">
  <div class="fss">
    Add Product
  </div>
  <div class="mtxs ptxs bss bwts bc-13">
    <%= form_tag v0_products_url(host: api_domain, subdomain: api_subdomain), remote: true, class: "js-lists-api-form js-products-form-new" do %>
      <%= hidden_field_tag :type, "AmazonProduct" %>
      <%= hidden_field_tag :id, nil %>
      <div class="mtm-plus">
        <div class="fsxxs">
          <%= label_tag :sku %>
        </div>
        <div class="fsxs">
          <%= text_field_tag :sku, nil, class: "paxxxs bss bwas bc-8 full-width" %>
          <div class="c-red hide js-lists-api-form-error" data-input-name="product[sku]"></div>
        </div>
      </div>
    <% end %>
    <%= form_tag add_product_v0_list_url(host: api_domain, subdomain: api_subdomain), remote: true, class: "js-lists-api-form js-lists-form-add-product" do %>
      <%= hidden_field_tag :id, @list.id %>
      <%= hidden_field_tag :user_id, current_user.id %>
      <%= hidden_field_tag :product_id, nil, data: { dependent: true, dependent_on_form: ".js-products-form-new", dependent_on_input: "id" } %>
      <div class="mtm">
        <%= submit_tag "Create", class: "paxxxs bss bwas bc-8 full-width", data: { disable_with: "Creating" } %>
      </div>
    <% end %>
  </div>
</div>