config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, controllers: { registrations: 'registrations'}
  resources :users, only: [:show, :edit, :update] do
    collection do
      get :thank_you
    end
  end
  resources :categories, only: [:show]
  resources :lists, only: [:new, :index, :show] do
    collection do
      get :empty
    end
  end
  resources :products, only: [:show]

  namespace :admin do
    root to: "lists#index"
    resources :lists
  end

  constraints subdomain: "api" do
    scope module: :api, defaults: { format: :json } do
      namespace :v0 do
        resources :likes, only: [:create, :update]
        resources :lists do
          member do
            post :add_product
          end
          resources :list_items, only: [:show]
        end
        resources :list_items
        resources :products
        resources :stores do
          collection do
            get :search
          end
        end
        resource :user do
          collection do
            post :like
            post :unlike
            post :comment
          end
        end
      end

      namespace :v1 do
        resources :comments, only: [:show]
        resources :likes, only: [:create, :update]
        resources :lists do
          member do
            post :add_product
          end
          resources :list_items, only: [:show]
        end
        resources :list_items
        resources :products
        resources :stores do
          collection do
            get :search
          end
        end

        resources :users, only: [:show]
      end
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>List</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="pbxxl bg-14">
    <div class="dvm lhm bg-4 bss bwbs bc-2">
      <div class="container phxs">
        <div class="c-15 fsl">
          <%= link_to "Lists", root_path %>
        </div>
      </div>
    </div>
    <div class="container phxs">
      <div class="row nmhxs">
        <div class="col-sm-3 phxs mtm">
          <%= link_to "Lists", admin_lists_path %>
        </div>
        <div class="col-sm-9 phxs mtm">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  <% if current_user %>
    <script>
      Lists.globals.apiToken = "<%= current_user.api_token || current_user.generate_api_token %>";
    </script>
  <% end %>
  <%= content_for :javascript %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= (content_for?(:title) ? "#{ content_for(:title) } | popjova" : "Make Life More Epic | popjova").html_safe %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta property="og:site_name" content="popjova"/>
  <%= content_for(:facebook_meta_tags) %>
  <meta property="og:description" content="Make Life More Epic. Products for gamers, suggested by gamers."/>
  <meta name='viewport' content='width=device-width, minimum-scale=1.0, maximum-scale=1.0'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:900,300' rel='stylesheet' type='text/css'>
  <%= content_for(:tracking_pixel) %>
</head>
<body>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=733767459997727&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <script>
    window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
    </script>
  <% if lists_in_need.count > 0 %>
    <%= link_to empty_lists_path do %>
      <div class="pvxxxxs bg-blue c-15 fsxxs text-center">
        <%= pluralize(lists_in_need.count, "list") %> <%= lists_in_need.count == 1 ? "is" : "are" %> awaiting your review. Click here to lend a hand.
      </div>
    <% end %>
  <% end %>
  <div class="dvl lhl bg-15 bss bwbs bc-13 no-select">
    <div class="container phs">
      <div class="row nmhxxxs">
        <div class="col-xs-6 col-sm-9 phxxxs">
          <table>
            <tr>
              <td>
                <div class="dvl no-overflow">
                  <%= link_to root_path do %>
                    <i class="icon-popjova lhl c-blue" style="font-size: 98px"></i>
                  <% end %>
                </div>
              </td>
              <td class="relative hidden-xs">
                <div class="js-toggle js-navbar-dropdown" data-toggle-target="#navbar-categories-dropdown" data-toggle-class="hide">
                  <div class="relative mls phxs dvl lhl c-1-active bss bwls bc-13 text-center pointer">
                    <table>
                      <tr>
                        <td>
                          <i class="fa fa-reorder fsxs"></i>
                        </td>
                        <td class="plxxxs">
                          categories
                        </td>
                      </tr>
                    </table>
                  </div>
                </div>
                <div id="navbar-categories-dropdown" class="absolute n-top left mls phxs bg-15 bss bwhs bwbs bc-13 zl hide" style="width: 380px;">
                  <div class="row nmhxs">
                    <% Category.all.order(name: :asc).each_slice((Category.count / 2.0).ceil) do |categories_col| %>
                      <div class="col-sm-6 phxs">
                        <% categories_col.each do |category| %>
                          <%= link_to category_path(category) do %>
                            <div class="lhm c-6 c-blue-hover text-left">
                              <%= category.name.html_safe %>
                            </div>
                          <% end %>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </td>
              <td>
                <%= link_to new_list_path do %>
                  <div class="phxs dvl lhl bss bwls bc-13 text-center">
                    <table>
                      <tr>
                        <td>
                          <i class="fa fa-file-text-o fsxs"></i>
                        </td>
                        <td class="plxxxs hidden-xs">
                          create list
                        </td>
                      </tr>
                    </table>
                  </div>
                <% end %>
              </td>
            </tr>
          </table>
        </div>
        <div class="col-xs-6 col-sm-3 phxxxs">
          <% if current_user %>
            <div class="relative pull-right">
              <div class="js-toggle" data-toggle-target="#navbar-account-dropdown" data-toggle-class="hide">
                <div class="phxs dvl lhl c-1-active bss bwhs bc-13 text-center pointer">
                  <table>
                    <tr>
                      <td>
                        <div class="das">
                          <%= image_tag current_user.profile_image, class: "img-responsive" %>
                        </div>
                      </td>
                      <td class="plxxxs fsxxxs">
                        <%= current_user.username %>
                      </td>
                    </tr>
                  </table>
                </div>
              </div>
              <div id="navbar-account-dropdown" class="absolute n-top right pvxs phm lhxs bg-15 bss bwhs bwbs bc-13 zl hide">
                <div class="mtxs-plus">
                  <%= link_to "profile", user_path(current_user), class: "c-6 c-blue-hover" %>
                </div>
                <div class="mtxs-plus">
                  <%= link_to "logout", destroy_user_session_path, method: :delete, class: "c-6 c-blue-hover" %>
                </div>
              </div>
            </div>
          <% else %>
            <%= link_to new_user_registration_path do %>
              <div class="phxxxs dvl lhl text-center pull-right">
                signup
              </div>
            <% end %>
            <%= link_to new_user_session_path do %>
              <div class="phxxxs dvl lhl text-center pull-right">
                login
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container phs">
    <table>
      <tr>
        <td class="ptxxxs">
          <div class="fb-like" data-href="https://www.facebook.com/superpopjova" data-layout="button" data-action="like" data-show-faces="true" data-share="false"></div>
        </td>
        <td class="plxs ptxxxs">
          <a class="twitter-follow-button" href="https://twitter.com/popjova" data-show-count="false" data-lang="en" data-show-screen-name="false">follow @popjova</a>
        </td>
        <td class="plxs">
          Every like helps<span class="hidden-xs"> grow the community of master looters</span>
        </td>
      </tr>
    </table>
  </div>
  <%= content_for :banner %>
  <div class="container phs pbxxxxl">
    <%= yield %>
  </div>
  <!-- <div class="pvxxl bg-3">
    <div class="container phs">
      <div class="row nmhs">
        <div class="col-sm-4 phs">
          <i class="icon-popjova c-15" style="font-size: 220px;"></i>
        </div>
        <div class="col-sm-8 phs">
          <div class="c-15 fsl">
            CONTACT
          </div>
          <div class="row nmhxs">
            <div class="col-sm-6 phxs">
              <div class="mtxxxs">
                <%= link_to "contact", "#", class: "c-14 c-blue-hover fsxs" %>
              </div>
              <div class="mtxxxs">
                <%= link_to "contact", "#", class: "c-14 c-blue-hover fsxs" %>
              </div>
            </div>
            <div class="col-sm-6 phxs">
              prou
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> -->
  <% if current_user %>
    <script>
      Lists.globals.apiToken = "<%= current_user.api_token || current_user.generate_api_token %>";
    </script>
  <% end %>
  <%= content_for :javascript %>
  <% unless Rails.env.development? %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-59128702-1', 'auto');
      ga('send', 'pageview');

    </script>
  <% end %>
</body>
</html>